name: github pages

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Python (pip)
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - run: uv run zensical build

      - name: Upload Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: website
          path: ./site

      - name: Find typos with codespell
        run: uvx codespell

  deploy:
    runs-on: ubuntu-latest
    needs: build
    concurrency: ci-${{ github.ref }}
    permissions:
      contents: write
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/source'
    steps:
      - name: Download Results
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: website
          path: ./site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: main
          cname: www.mingw-w64.org
